// <auto-generated />
using System;
using IPSApps.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace IPSApps.API.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("IPSApps.API.Entities.Building", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Buildings");
                });

            modelBuilder.Entity("IPSApps.API.Entities.Floor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("BuildingId");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("Map");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId");

                    b.ToTable("Floors");
                });

            modelBuilder.Entity("IPSApps.API.Entities.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("FloorId");

                    b.Property<bool>("IsDeleted");

                    b.Property<int?>("LocationTypesId");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("FloorId");

                    b.HasIndex("LocationTypesId");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("IPSApps.API.Entities.LocationType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("LocationTypes");
                });

            modelBuilder.Entity("IPSApps.API.Entities.Floor", b =>
                {
                    b.HasOne("IPSApps.API.Entities.Building", "Building")
                        .WithMany()
                        .HasForeignKey("BuildingId");
                });

            modelBuilder.Entity("IPSApps.API.Entities.Location", b =>
                {
                    b.HasOne("IPSApps.API.Entities.Floor", "Floor")
                        .WithMany()
                        .HasForeignKey("FloorId");

                    b.HasOne("IPSApps.API.Entities.LocationType", "LocationTypes")
                        .WithMany()
                        .HasForeignKey("LocationTypesId");
                });
#pragma warning restore 612, 618
        }
    }
}
